### ISSUE TITLE
Elasticsearch index arg invalid 

### ISSUE THREAD

**Issue by ciusji** [LeonaLog/leona#45]
Elasticsearch index arg invalid:

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/_cat/indices/graylog_*] contains unrecognized parameter: [expand_wildcards]"}],"type":"illegal_argument_exception","reason":"request [/_cat/indices/graylog_*] contains unrecognized parameter: [expand_wildcards]"},"status":400}

Detail excepitons below:

at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.convertResponse(RestClient.java:302) ~[?:?]
at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:272) ~[?:?]
at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) ~[?:?]
at org.graylog.storage.elasticsearch7.cat.CatApi.lambda$perform$4(CatApi.java:92) ~[?:?]
at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:110) ~[?:?]

**Comment by ciusji** [comment]
We do support ES 7.7+
